---
title: "Titanic"
output: html_notebook
---

```{r}
library(rpart)
library(rpart.plot)
library(tidyverse)
library(GGally)
library(splitstackshape)
library(modelr)
library(caret)

titanic_set <- read_csv('data/titanic_decision_tree_data.csv')

shuffle_index <- sample(1:nrow(titanic_set))

# shuffle the data so class order isn't in order - need this for training/testing split later on 
titanic_set <- titanic_set[shuffle_index, ]
```

```{r}
titanic_clean <- titanic_set %>%
  filter(survived %in% c(0,1)) %>%
# Convert to factor level
    mutate(sex = as.factor(sex), 
           age_status = as.factor(if_else(age <= 16, "child", "adult")),
         class = factor(pclass, levels = c(3,2,1), labels = c("Lower", "Middle", "Upper")), 
           survived_flag = factor(survived, levels = c(0,1), labels = c("No", "Yes")), 
           port_embarkation = as.factor(embarked)) %>%
  select(sex, age_status, class, port_embarkation, sib_sp, parch, survived_flag) %>%
  na.omit()
```

```{r}
ggpairs(titanic_clean)
```

```{r}
titanic_split <- stratified(indt = titanic_clean,
           group = "survived_flag",
           size = 0.8,
           bothSets = TRUE
           )

titanic_train <- titanic_split$SAMP1
titanic_test <- titanic_split$SAMP2
```

```{r}
titanic_fit <- rpart(
  formula = survived_flag ~ .,
  data = titanic_train,
  method = "class"
)

rpart.plot(
  titanic_fit,
  yesno = 2,
  fallen.leaves = TRUE,
  faclen = 6,
  digit = 4
)
```
```{r}
titanic_test_pred <- titanic_test %>% 
  add_predictions(titanic_fit, type = "class")

conf_mat <- confusionMatrix(titanic_test_pred$pred, titanic_test_pred$survived_flag)

conf_mat
```

